### auth.http

### Variables (Update these after logging in)
@baseUrl = http://localhost:8000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgzMzE1NDIxLCJpYXQiOjE3ODMzMTUxMjEsImp0aSI6IjVjMjNlZWYzNjY5OTRiMmY5M2I1MWVkYTEwMTg0YzM2IiwidXNlcl9pZCI6IjEifQ.i9iN8sqiSAE95P6ENrwJHOzOWTjBJe-BZvLd3lczmLY
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MzQwMDIwMiwiaWF0IjoxNzgzMzEzODAyLCJqdGkiOiI2ZGE5NzViMDQ3N2Y0ZTgzYjNmZmU0NDZhMzMxYzM3YSIsInVzZXJfaWQiOiIxIn0.r8Qo_lHmEkwC6dZqGZOsjHBvkzW3DaNXzgZVkxmxfmw

### Register a new user
POST {{baseUrl}}/api/auth/register/
Content-Type: application/json

{
    "username": "alisher",
    "email": "alisher@example.com",
    "password": "password123"
}

### Login
POST {{baseUrl}}/api/v1/staff/auth/login/
Content-Type: application/json

{
    "email": "admin@a.com",
    "password": "admin"
}

### Get Current User Info
GET {{baseUrl}}/api/auth/me/
Authorization: Bearer {{accessToken}}

### Refresh Access Token
POST {{baseUrl}}/api/auth/refresh/
Content-Type: application/json

{
    "refresh": "{{refreshToken}}"
}

### Post new todo
POST {{baseUrl}}/api/todos/
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "title": "Learn Django2"
}
### Post new todo
POST {{baseUrl}}/api/todos/
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "title": "Learn React"
}
### Post new todo
POST {{baseUrl}}/api/todos/
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "title": " "
}
### Get list of todos
GET {{baseUrl}}/api/todos/
Content-Type: application/json
Authorization: Bearer {{accessToken}}
### Get list of todos
GET {{baseUrl}}/api/todos/?search=django
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### Post update todo
PATCH {{baseUrl}}/api/todos/1/
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "completed": true
}

### Delete update todo
DELETE {{baseUrl}}/api/todos/1/
Content-Type: application/json
Authorization: Bearer {{accessToken}}
