# Generated by Django 6.0.7 on 2026-07-31 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type'], name='activities__activit_8e7970_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['status'], name='activities__status_b1bb4f_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['owner'], name='activities__owner_i_ae3644_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['content_type', 'object_id'], name='activities__content_32e159_idx'),
        ),
    ]
