# Generated by Django 6.0.7 on 2026-07-31 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['content_type', 'object_id'], name='notes_note_content_7500a1_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['created_by'], name='notes_note_created_f92d5a_idx'),
        ),
    ]
